### ISSUE TITLE
Redesign LED UI

### ISSUE THREAD

**Issue by mattykakes** [mattykakes/QPlumbob#43]
Use a circular design easily controlled by a thumb instead of the current pages and sliders which are a remnant of a previous use case

![image](https://user-images.githubusercontent.com/31940423/92067345-12760300-ed72-11ea-80b4-bd6e2d66d341.png)

**Comment by mattrussmill** [comment]
obtain mouse position

https://stackoverflow.com/questions/24755292/get-mouse-position-relative-to-pie-chart-equation

**Comment by mattrussmill** [comment]
How to draw with canvas
https://stackoverflow.com/questions/26044801/draw-an-arc-circle-sector-in-qml
https://doc.qt.io/qt-5/qml-qtquick-context2d.html#arc-method

**Comment by mattrussmill** [comment]
make center of circle white (very light gray) using a radial gradient centered at the same point as the wheel to select color intensity. Value should be a separate slider. If it is not setup like this, white light would never be an option.

Place horizontal hsv value slider at bottom and pulse/phase controls below color wheel.

**Comment by mattrussmill** [comment]
Good enough for this one-off project
